#!/usr/bin/env python3
"""Generate independently checked application data; deterministic and byte reproducible."""
from pathlib import Path
import random
import sys
rng=random.Random(913)
shapes=[(4,4,4),(8,8,8),(4,4,16),(5,7,19),(3,2,0),(1,1,1),(9,5,33),(4,4,16)]
out=['// Generated by tests/matrix/workload.py. Do not edit expected values.\n']
for t,(m,n,k) in enumerate(shapes):
    raw=[rng.randrange(-128,128) for _ in range(m*k)]
    b=[rng.randrange(-128,128) for _ in range(k*n)]
    if t==0: raw=[(i%5)-2 for i in range(m*k)]; b=[(i%3)-1 for i in range(k*n)]
    if t==7: raw=[127]*(m*k); b=[-128]*(k*n)
    a=[((x+1+128)%256)-128 for x in raw]
    c=[(sum(a[i*k+p]*b[p*n+j] for p in range(k))+3)&0xffffffff
       for i in range(m) for j in range(n)]
    for name,values,typ in [('raw',raw,'int8_t'),('b',b,'int8_t'),('expected',c,'uint32_t')]:
        out.append(f'static const {typ} {name}_{t}[] = {{'+','.join(str(v)+('u' if typ=='uint32_t' else '') for v in (values or [0]))+'};\n')
out.append('struct workload { size_t m,n,k; const int8_t *raw,*b; const uint32_t *expected; };\n')
out.append('static const struct workload cases[] = {\n')
for t,(m,n,k) in enumerate(shapes): out.append(f'  {{{m},{n},{k},raw_{t},b_{t},expected_{t}}},\n')
out.append('};\n')
Path(sys.argv[1]).write_text(''.join(out))
